// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ehVdMWYdhyrQEHqpc1L0QofiHFUawH8',
    appId: '1:91678987925:web:419f93b8c413d292fdad9c',
    messagingSenderId: '91678987925',
    projectId: 'smart-pantry-ef421',
    authDomain: 'smart-pantry-ef421.firebaseapp.com',
    storageBucket: 'smart-pantry-ef421.firebasestorage.app',
    measurementId: 'G-4H1HS2GS7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvoUbOgfy7oSq-XENbChmIhBdIxSt7zvg',
    appId: '1:91678987925:android:c15f9e8a25dc6f4dfdad9c',
    messagingSenderId: '91678987925',
    projectId: 'smart-pantry-ef421',
    storageBucket: 'smart-pantry-ef421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrdqqQVjwe2wJfO6yVTVOWxX9G3pBYNrs',
    appId: '1:91678987925:ios:408735ad5cab4552fdad9c',
    messagingSenderId: '91678987925',
    projectId: 'smart-pantry-ef421',
    storageBucket: 'smart-pantry-ef421.firebasestorage.app',
    iosBundleId: 'com.example.smartPantry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrdqqQVjwe2wJfO6yVTVOWxX9G3pBYNrs',
    appId: '1:91678987925:ios:408735ad5cab4552fdad9c',
    messagingSenderId: '91678987925',
    projectId: 'smart-pantry-ef421',
    storageBucket: 'smart-pantry-ef421.firebasestorage.app',
    iosBundleId: 'com.example.smartPantry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-ehVdMWYdhyrQEHqpc1L0QofiHFUawH8',
    appId: '1:91678987925:web:a97c67f972529f15fdad9c',
    messagingSenderId: '91678987925',
    projectId: 'smart-pantry-ef421',
    authDomain: 'smart-pantry-ef421.firebaseapp.com',
    storageBucket: 'smart-pantry-ef421.firebasestorage.app',
    measurementId: 'G-BMC7Z69R2N',
  );
}
